In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from ipywidgets import interact

In [2]:
data= pd.read_csv('adult (2).csv')

In [3]:
data.head()


39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

In [4]:
data.columns

Index(['39', ' State-gov', ' 77516', ' Bachelors', ' 13', ' Never-married',
       ' Adm-clerical', ' Not-in-family', ' White', ' Male', ' 2174', ' 0',
       ' 40', ' United-States', ' <=50K'],
      dtype='object')

In [5]:
data_cols = ['age','workclass','fnlwgt','education','education_num','marital_status','occupation','relationship','race','sex','capital_gain','capital_loss', 'hours_per_week', 'native_country', 'income']

In [6]:
data.columns= data_cols


In [7]:
data.head()

age          workclass  fnlwgt   education  education_num  \
0   50   Self-emp-not-inc   83311   Bachelors             13   
1   38            Private  215646     HS-grad              9   
2   53            Private  234721        11th              7   
3   28            Private  338409   Bachelors             13   
4   37            Private  284582     Masters             14   

        marital_status          occupation    relationship    race      sex  \
0   Married-civ-spouse     Exec-managerial         Husband   White     Male   
1             Divorced   Handlers-cleaners   Not-in-family   White     Male   
2   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
3   Married-civ-spouse      Prof-specialty            Wife   Black   Female   
4   Married-civ-spouse     Exec-managerial            Wife   White   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0             0             0              13   United-States   <=50K  
1             0             0              40   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40            Cuba   <=50K  
4             0             0              40   United-States   <=50K

In [8]:
data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32560 entries, 0 to 32559
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32560 non-null  int64 
 1   workclass       32560 non-null  object
 2   fnlwgt          32560 non-null  int64 
 3   education       32560 non-null  object
 4   education_num   32560 non-null  int64 
 5   marital_status  32560 non-null  object
 6   occupation      32560 non-null  object
 7   relationship    32560 non-null  object
 8   race            32560 non-null  object
 9   sex             32560 non-null  object
 10  capital_gain    32560 non-null  int64 
 11  capital_loss    32560 non-null  int64 
 12  hours_per_week  32560 non-null  int64 
 13  native_country  32560 non-null  object
 14  income          32560 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
labelencoder_data = LabelEncoder()


In [12]:
data = data.apply(LabelEncoder().fit_transform)

In [13]:
data

age  workclass  fnlwgt  education  education_num  marital_status  \
0       33          6    2925          9             12               2   
1       21          4   14085         11              8               0   
2       36          4   15335          1              6               2   
3       11          4   19354          9             12               2   
4       20          4   17699         12             13               2   
...    ...        ...     ...        ...            ...             ...   
32555   10          4   16527          7             11               2   
32556   23          4    8079         11              8               2   
32557   41          4    7882         11              8               6   
32558    5          4   12880         11              8               4   
32559   35          5   17824         11              8               2   

       occupation  relationship  race  sex  capital_gain  capital_loss  \
0               4             0     4    1             0             0   
1               6             1     4    1             0             0   
2               6             0     2    1             0             0   
3              10             5     2    0             0             0   
4               4             5     4    0             0             0   
...           ...           ...   ...  ...           ...           ...   
32555          13             5     4    0             0             0   
32556           7             0     4    1             0             0   
32557           1             4     4    0             0             0   
32558           1             3     4    1             0             0   
32559           4             5     4    0           108             0   

       hours_per_week  native_country  income  
0                  12              39       0  
1                  39              39       0  
2                  39              39       0  
3                  39               5       0  
4                  39              39       0  
...               ...             ...     ...  
32555              37              39       0  
32556              39              39       1  
32557              39              39       0  
32558              19              39       0  
32559              39              39       1  

[32560 rows x 15 columns]

In [14]:
x= data.values

In [15]:
y= data['income'].values

In [16]:
x= np.delete(x,14,axis=1)


In [17]:
x

array([[   33,     6,  2925, ...,     0,    12,    39],
       [   21,     4, 14085, ...,     0,    39,    39],
       [   36,     4, 15335, ...,     0,    39,    39],
       ...,
       [   41,     4,  7882, ...,     0,    39,    39],
       [    5,     4, 12880, ...,     0,    19,    39],
       [   35,     5, 17824, ...,     0,    39,    39]])

In [18]:
y

array([0, 0, 0, ..., 0, 0, 1])

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [20]:
X_train

array([[   17,     4,  5344, ...,     0,    64,    39],
       [   37,     6,  4643, ...,     0,    49,    39],
       [   18,     4, 12534, ...,     0,    53,    39],
       ...,
       [   26,     6, 18578, ...,     0,    29,    39],
       [    4,     7,  1038, ...,     0,    49,    39],
       [   32,     5,  4672, ...,     0,    31,    39]])

In [21]:
X_test

array([[   23,     5, 12043, ...,     0,    39,    39],
       [   29,     4, 11405, ...,     0,    44,    39],
       [   16,     0, 12985, ...,     0,    39,    13],
       ...,
       [   50,     0, 11969, ...,     0,    10,    39],
       [    7,     4,   740, ...,     0,    36,    39],
       [   36,     4, 16568, ...,     0,    39,    39]])

In [22]:
y_train

array([1, 0, 0, ..., 0, 0, 0])

In [23]:
y_test

array([1, 0, 0, ..., 0, 0, 0])

In [24]:
from sklearn import tree
dt_clf = tree.DecisionTreeClassifier(max_depth=5)
dt_clf.fit(X_train, y_train)
dt_clf.score(X_test, y_test)
y_pred = dt_clf.predict(X_test)
dt_clf.score(X_test, y_test)

0.8508906633906634

In [25]:
y_pred = dt_clf.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)


array([[4722,  235],
       [ 736,  819]])

In [26]:
from sklearn import ensemble
rf_clf = ensemble.RandomForestClassifier(n_estimators=100)
rf_clf.fit(X_train, y_train)
rf_clf.score(X_test, y_test)

0.8558046683046683

In [27]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train, y_train)
knn_clf.score(X_test, y_test)

0.7612100737100738

In [28]:
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression()
lr_clf.fit(X_train, y_train)
lr_clf.score(X_test, y_test)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


0.784551597051597

In [29]:
from sklearn.metrics import accuracy_score
print("accuracy score:", accuracy_score(y_test, y_pred))

accuracy score: 0.8508906633906634


In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4722,  235],
       [ 736,  819]])

In [31]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.95      0.91      4957
           1       0.78      0.53      0.63      1555

    accuracy                           0.85      6512
   macro avg       0.82      0.74      0.77      6512
weighted avg       0.84      0.85      0.84      6512

